# Netlify Build Configuration
[build]
  # Directory with the build output
  publish = "build"
  
  # Build command
  command = "npm run build"

# Netlify Forms Configuration
[build.environment]
  # Ensure Node.js version compatibility
  NODE_VERSION = "18"

# Redirect rules for React Router (if you add routing later)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache optimization
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"