// Shared styles for the entire application
export const styles = {
  heroSection: {
    background: 'linear-gradient(135deg, #0f172a 0%, #1e40af 50%, #4338ca 100%)',
    minHeight: '85vh',
    color: 'white',
    padding: 'clamp(4rem, 10vw, 8rem) clamp(0.5rem, 2vw, 1rem)',
    position: 'relative' as const,
    overflow: 'hidden',
  },
  heroTitle: {
    fontSize: 'clamp(3rem, 8vw, 6rem)',
    fontWeight: 900,
    background: 'linear-gradient(to right, #ffffff, #bfdbfe, #ddd6fe)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    marginBottom: '1.5rem',
    lineHeight: 1.1,
  },
  button: {
    background: 'linear-gradient(to right, #facc15, #eab308)',
    color: '#0f172a',
    padding: '1rem 2.5rem',
    borderRadius: '0.75rem',
    fontWeight: 'bold',
    border: 'none',
    cursor: 'pointer',
    fontSize: '1.125rem',
    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
    transition: 'all 0.3s ease',
  },
  nav: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    zIndex: 50,
    background: 'rgba(183, 146, 146, 0.22)',
    backdropFilter: 'blur(10px)',
    borderBottom: '1px solid rgba(255, 255, 255, 0.2)',
    padding: 'clamp(1rem, 2vw, 1rem) 0',
  },
  serviceCard: {
    background: 'rgba(255, 255, 255, 0.7)',
    backdropFilter: 'blur(10px)',
    padding: 'clamp(1.5rem, 4vw, 2rem)',
    borderRadius: '1rem',
    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
    border: '1px solid rgba(148, 163, 184, 0.5)',
    transition: 'all 0.3s ease',
    cursor: 'pointer',
  },
  iconContainer: {
    width: '3rem',
    height: '3rem',
    borderRadius: '0.75rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '1.5rem',
    color: 'white',
  },
  pageContainer: {
    minHeight: '100vh',
    background: '#f8fafc',
    padding: '5rem 1rem',
    paddingTop: '8rem', // Extra padding to account for fixed nav
  },
  card: {
    background: 'white',
    borderRadius: '0.5rem',
    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
    padding: '2rem',
    marginBottom: '2rem',
  },
  // Page layout styles
  contentContainer: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 1rem',
  },
  sectionTitle: {
    fontSize: 'clamp(2rem, 6vw, 2.5rem)',
    fontWeight: 'bold',
    textAlign: 'center' as const,
    marginBottom: 'clamp(2rem, 5vw, 3rem)',
    color: '#111827',
  },
  subsectionTitle: {
    fontSize: 'clamp(1.5rem, 4vw, 1.875rem)',
    fontWeight: 'bold',
    color: '#1e40af',
    marginBottom: 'clamp(1rem, 3vw, 1.5rem)',
  },
  // Text styles
  bodyText: {
    fontSize: '1.125rem',
    color: '#374151',
    lineHeight: 1.7,
    marginBottom: '1.5rem',
  },
  smallText: {
    fontSize: '0.875rem',
    color: '#6b7280',
  },
  // Layout helpers
  grid2: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(clamp(280px, 85vw, 300px), 1fr))',
    gap: 'clamp(1.5rem, 4vw, 2rem)',
  },
  gridContact: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(clamp(320px, 90vw, 400px), 1fr))',
    gap: 'clamp(2rem, 5vw, 3rem)',
  },
  gridServices: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(clamp(250px, 90vw, 320px), 1fr))',
    gap: 'clamp(1rem, 3vw, 1.5rem)',
  },
  gridForm: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '1rem',
    marginBottom: '1rem',
  },
  flexCenter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  flexStart: {
    display: 'flex',
    alignItems: 'start',
  },
  flexBetween: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  // ABOUT PAGE STYLES
  aboutContainer: {
    maxWidth: '64rem',
    margin: '0 auto',
  },
  missionCard: {
    background: 'white',
    borderRadius: '0.5rem',
    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
    padding: '2rem',
  },
  valuesCard: {
    background: 'white',
    borderRadius: '0.5rem',
    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
    padding: '2rem',
  },
  valuesList: {
    color: '#374151',
    listStyle: 'none',
    padding: 0,
  },
  valuesListItem: {
    display: 'flex',
    alignItems: 'start',
    marginBottom: '0.5rem',
  },
  valuesIcon: {
    height: '1.25rem',
    width: '1.25rem',
    color: '#2563eb',
    marginRight: '0.5rem',
    marginTop: '0.125rem',
    flexShrink: 0,
  },
  expertiseTitle: {
    fontSize: '1.25rem',
    fontWeight: 600,
    color: '#111827',
    marginBottom: '0.75rem',
  },
  expertiseList: {
    color: '#374151',
    lineHeight: 1.6,
  },
  licensedSection: {
    background: '#1e40af',
    color: 'white',
    borderRadius: '0.5rem',
    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
    padding: '2rem',
    textAlign: 'center' as const,
  },
  licensedTitle: {
    fontSize: '1.5rem',
    fontWeight: 'bold',
    marginBottom: '1rem',
  },
  licensedText: {
    color: '#bfdbfe',
    marginBottom: '1rem',
  },
  licensedBadges: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '2rem',
    fontSize: '0.875rem',
    flexWrap: 'wrap' as const,
  },
  licensedBadge: {
    textAlign: 'center' as const,
  },
  licensedIcon: {
    height: '2rem',
    width: '2rem',
    color: '#facc15',
    margin: '0 auto 0.5rem',
  },
  // CONTACT PAGE STYLES
  contactContainer: {
    maxWidth: '72rem',
    margin: '0 auto',
  },
  contactIntro: {
    color: '#374151',
    marginBottom: '2rem',
    fontSize: '1.125rem',
    lineHeight: 1.6,
  },
  contactInfoSection: {
    marginBottom: '2rem',
  },
  contactInfoItem: {
    display: 'flex',
    alignItems: 'start',
    marginBottom: '1.5rem',
  },
  contactIcon: {
    height: '1.5rem',
    width: '1.5rem',
    color: '#2563eb',
    marginRight: '1rem',
    marginTop: '0.125rem',
    flexShrink: 0,
  },
  contactInfoTitle: {
    fontWeight: 600,
    color: '#111827',
    marginBottom: '0.25rem',
  },
  contactInfoText: {
    color: '#374151',
    marginBottom: '0.25rem',
  },
  contactInfoSubtext: {
    fontSize: '0.875rem',
    color: '#6b7280',
  },
  businessHours: {
    padding: '1.5rem',
    background: '#eff6ff',
    borderRadius: '0.5rem',
    border: '1px solid #dbeafe',
  },
  businessHoursTitle: {
    fontWeight: 'bold',
    color: '#1e40af',
    marginBottom: '0.75rem',
  },
  businessHoursText: {
    color: '#374151',
    lineHeight: 1.6,
  },
  businessHoursEmergency: {
    fontSize: '0.875rem',
    color: '#2563eb',
    fontWeight: 500,
    marginTop: '0.5rem',
  },
  // Form styles
  formCard: {
    background: 'white',
    borderRadius: '0.5rem',
    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
    padding: '2rem',
  },
  formSection: {
    marginBottom: '1.5rem',
  },
  formInput: {
    width: '100%',
    padding: '0.75rem',
    border: '1px solid #d1d5db',
    borderRadius: '0.375rem',
    fontSize: '1rem',
    outline: 'none',
    transition: 'border-color 0.3s ease',
  },
  formTextarea: {
    width: '100%',
    padding: '0.75rem',
    border: '1px solid #d1d5db',
    borderRadius: '0.375rem',
    fontSize: '1rem',
    outline: 'none',
    transition: 'border-color 0.3s ease',
    resize: 'vertical' as const,
    minHeight: '100px',
  },
  formLabel: {
    display: 'block',
    fontSize: '0.875rem',
    fontWeight: 500,
    color: '#374151',
    marginBottom: '0.5rem',
  },
  submitButton: {
    width: '100%',
    background: '#2563eb',
    color: 'white',
    padding: '0.75rem 1rem',
    borderRadius: '0.375rem',
    border: 'none',
    fontWeight: 600,
    cursor: 'pointer',
    fontSize: '1rem',
    transition: 'background-color 0.3s ease',
  },
  // FOOTER STYLES
  footer: {
    background: '#111827',
    color: 'white',
    padding: '3rem 1rem',
  },
  footerContainer: {
    maxWidth: '1200px',
    margin: '0 auto',
  },
  footerGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '2rem',
    marginBottom: '2rem',
  },
  footerBrand: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '1rem',
  },
  footerLogo: {
    height: '2rem',
    width: '2rem',
    color: '#facc15',
    marginRight: '0.75rem',
  },
  footerBrandText: {
    fontWeight: 'bold',
    fontSize: '1.25rem',
  },
  footerDescription: {
    color: '#d1d5db',
    marginBottom: '1rem',
    lineHeight: 1.6,
  },
  footerTagline: {
    fontSize: '0.875rem',
    color: '#9ca3af',
  },
  footerSectionTitle: {
    fontWeight: 'bold',
    fontSize: '1.125rem',
    marginBottom: '1rem',
  },
  footerList: {
    color: '#d1d5db',
    listStyle: 'none',
    padding: 0,
    lineHeight: 1.8,
  },
  footerContactList: {
    color: '#d1d5db',
  },
  footerContactItem: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '0.75rem',
  },
  footerContactIcon: {
    height: '1rem',
    width: '1rem',
    marginRight: '0.5rem',
    flexShrink: 0,
  },
  footerBottom: {
    borderTop: '1px solid #374151',
    paddingTop: '2rem',
    textAlign: 'center' as const,
    color: '#9ca3af',
  },
};